/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.calculator;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.script.ScriptEngine;
import javax.script.ScriptEngineManager;
import javax.script.ScriptException;


/**
 *
 * @author Nishant
 */
public class CalculatorUI extends javax.swing.JFrame {

    /**
     * Creates new form CalculatorUI
     */
    char Coper = ' ';
    String num2="";
    boolean haveDec = false;
    String lastButtonPressed = "";
    
    double res = 0,n1=0,n2=0;
    public CalculatorUI() {
        this.setTitle("Calculator Boss");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jB2 = new javax.swing.JButton();
        jB3 = new javax.swing.JButton();
        jB1 = new javax.swing.JButton();
        jB4 = new javax.swing.JButton();
        jB5 = new javax.swing.JButton();
        jB6 = new javax.swing.JButton();
        jB7 = new javax.swing.JButton();
        jB8 = new javax.swing.JButton();
        jB9 = new javax.swing.JButton();
        jB00 = new javax.swing.JButton();
        jB0 = new javax.swing.JButton();
        jBdec = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jBequal = new javax.swing.JButton();
        jBadd = new javax.swing.JButton();
        jBsub = new javax.swing.JButton();
        jBac = new javax.swing.JButton();
        jBdiv = new javax.swing.JButton();
        jBequal1 = new javax.swing.JButton();
        jBdel = new javax.swing.JButton();
        jBmul = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMtype = new javax.swing.JMenu();
        jMIScientific = new javax.swing.JMenuItem();
        jMabout = new javax.swing.JMenu();
        jMInisH = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jB2.setText("2");
        jB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB2ActionPerformed(evt);
            }
        });

        jB3.setText("3");
        jB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB3ActionPerformed(evt);
            }
        });

        jB1.setText("1");
        jB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB1ActionPerformed(evt);
            }
        });

        jB4.setText("4");
        jB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB4ActionPerformed(evt);
            }
        });

        jB5.setText("5");
        jB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB5ActionPerformed(evt);
            }
        });

        jB6.setText("6");
        jB6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB6ActionPerformed(evt);
            }
        });

        jB7.setText("7");
        jB7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB7ActionPerformed(evt);
            }
        });

        jB8.setText("8");
        jB8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB8ActionPerformed(evt);
            }
        });

        jB9.setText("9");
        jB9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB9ActionPerformed(evt);
            }
        });

        jB00.setText("00");
        jB00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB00ActionPerformed(evt);
            }
        });

        jB0.setText("0");
        jB0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB0ActionPerformed(evt);
            }
        });

        jBdec.setText(".");
        jBdec.setName("jBdec"); // NOI18N
        jBdec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBdecActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jB1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jB2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jB3, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jB00, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                            .addComponent(jB7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jB4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jB5, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                            .addComponent(jB8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jB0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jB6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jB9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBdec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jB00, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB0, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jBdec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jBequal.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jBequal.setForeground(new java.awt.Color(0, 51, 51));
        jBequal.setText("=");
        jBequal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBequalActionPerformed(evt);
            }
        });

        jBadd.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jBadd.setForeground(new java.awt.Color(0, 204, 0));
        jBadd.setText("+");
        jBadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBaddActionPerformed(evt);
            }
        });

        jBsub.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jBsub.setForeground(new java.awt.Color(255, 102, 102));
        jBsub.setText("-");
        jBsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsubActionPerformed(evt);
            }
        });

        jBac.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBac.setForeground(new java.awt.Color(255, 0, 0));
        jBac.setText("AC");
        jBac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBacActionPerformed(evt);
            }
        });

        jBdiv.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jBdiv.setForeground(new java.awt.Color(255, 51, 0));
        jBdiv.setText("/");
        jBdiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBdivActionPerformed(evt);
            }
        });

        jBequal1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jBequal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBequal1ActionPerformed(evt);
            }
        });

        jBdel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBdel.setForeground(new java.awt.Color(255, 51, 51));
        jBdel.setText("<Del");
        jBdel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBdelActionPerformed(evt);
            }
        });

        jBmul.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jBmul.setForeground(new java.awt.Color(0, 204, 51));
        jBmul.setText("*");
        jBmul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmulActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jBac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBequal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(jBsub, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBadd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jBdel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBequal1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBdiv, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jBmul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBadd, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBmul, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBsub, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBdiv, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jBequal, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jBequal1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBdel, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel2.setText("nisH");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(240, 240, 240));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("0");
        jLabel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLabel1ActionPerformed(evt);
            }
        });

        jMtype.setText("Type");
        jMtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMtypeActionPerformed(evt);
            }
        });

        jMIScientific.setText("Scientific");
        jMIScientific.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIScientificActionPerformed(evt);
            }
        });
        jMtype.add(jMIScientific);

        jMenuBar1.add(jMtype);

        jMabout.setText("About");
        jMabout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMaboutActionPerformed(evt);
            }
        });

        jMInisH.setText("nisH");
        jMInisH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMInisHActionPerformed(evt);
            }
        });
        jMabout.add(jMInisH);

        jMenuBar1.add(jMabout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB1ActionPerformed
        // TODO add your handling code here:
        if(lastButtonPressed.equals("jBequal"))
            jLabel1.setText(""+0);
        String be = jLabel1.getText();
        if(be.equals("0"))
           be = "1";
        else
           be += "1";
        jLabel1.setText(be);
        lastButtonPressed = "jB1";
    }//GEN-LAST:event_jB1ActionPerformed

    private void jB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB4ActionPerformed
        // TODO add your handling code here:
        if(lastButtonPressed.equals("jBequal"))
            jLabel1.setText(""+0);
        String be = jLabel1.getText();
        if(be.equals("0"))
           be = "4";
        else
           be += "4";
        lastButtonPressed = "jB2";
        jLabel1.setText(be);
    }//GEN-LAST:event_jB4ActionPerformed

    private void jB7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB7ActionPerformed
        // TODO add your handling code here:
        if(lastButtonPressed.equals("jBequal"))
            jLabel1.setText(""+0);
        String be = jLabel1.getText();
        if(be.equals("0"))
           be = "7";
        else
           be += "7";
        jLabel1.setText(be);
        lastButtonPressed = "jB7";
    }//GEN-LAST:event_jB7ActionPerformed

    private void jB9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB9ActionPerformed
        // TODO add your handling code here:
        if(lastButtonPressed.equals("jBequal"))
            jLabel1.setText(""+0);
        String be = jLabel1.getText();
        if(be.equals("0"))
           be = "9";
        else
           be += "9";
        jLabel1.setText(be);
        lastButtonPressed = "jB9";
    }//GEN-LAST:event_jB9ActionPerformed

    private void jBequalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBequalActionPerformed
        // TODO add your handling code here:
                // create a script engine manager
        ScriptEngineManager factory = new ScriptEngineManager();
        // create a JavaScript engine
        ScriptEngine engine = factory.getEngineByName("JavaScript");
        
        double d =0;
        
        try {
            d = (Double)engine.eval(jLabel1.getText()+"+0.0");
        } catch (ScriptException ex) {
            Logger.getLogger(CalculatorUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        jLabel1.setText(""+d);
        haveDec = true;
        lastButtonPressed = "jBequal";
    }//GEN-LAST:event_jBequalActionPerformed

    private void jBsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsubActionPerformed
        // TODO add your handling code here:
        String be = jLabel1.getText();
        if(lastButtonPressed.equals("jBequal"))
            jLabel1.setText(""+0);
        if(be.equals("0"))
           be = "-";
        else{
           Coper = '-';
           be += "-";
        }
        haveDec = false;
        lastButtonPressed = "jBsub";
        jLabel1.setText(be);
    }//GEN-LAST:event_jBsubActionPerformed

    private void jB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB2ActionPerformed
        // TODO add your handling code here:
        if(lastButtonPressed.equals("jBequal"))
            jLabel1.setText(""+0);
        String be = jLabel1.getText();
        if(be.equals("0"))
           be = "2";
        else
           be += "2";
        jLabel1.setText(be);
        lastButtonPressed = "jB2";
    }//GEN-LAST:event_jB2ActionPerformed

    private void jB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB3ActionPerformed
        // TODO add your handling code here:
        if(lastButtonPressed.equals("jBequal"))
            jLabel1.setText(""+0);
        String be = jLabel1.getText();
        if(be.equals("0"))
           be = "3";
        else
           be += "3";
        jLabel1.setText(be);
        lastButtonPressed = "jB3";
    }//GEN-LAST:event_jB3ActionPerformed

    private void jB5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB5ActionPerformed
        // TODO add your handling code here:
        if(lastButtonPressed.equals("jBequal"))
            jLabel1.setText(""+0);
        String be = jLabel1.getText();
        if(be.equals("0"))
           be = "5";
        else
           be += "5";
        jLabel1.setText(be);
        lastButtonPressed = "jB5";
    }//GEN-LAST:event_jB5ActionPerformed

    private void jB6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB6ActionPerformed
        // TODO add your handling code here:
        if(lastButtonPressed.equals("jBequal"))
            jLabel1.setText(""+0);
        String be = jLabel1.getText();
        if(be.equals("0"))
           be = "6";
        else
           be += "6";
        jLabel1.setText(be);
        lastButtonPressed = "jB6";
    }//GEN-LAST:event_jB6ActionPerformed

    private void jB8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB8ActionPerformed
        // TODO add your handling code here:
        if(lastButtonPressed.equals("jBequal"))
            jLabel1.setText(""+0);
        String be = jLabel1.getText();
        if(be.equals("0"))
           be = "8";
        else
           be += "8";
        jLabel1.setText(be);
        lastButtonPressed = "jB8";
    }//GEN-LAST:event_jB8ActionPerformed

    private void jB00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB00ActionPerformed
        // TODO add your handling code here:
        if(lastButtonPressed.equals("jBequal"))
            jLabel1.setText(""+0);
        String be = jLabel1.getText();
        if(be.equals("0"))
           be = "0";
        else
           be += "00";
        jLabel1.setText(be);
        lastButtonPressed = "jB00";
    }//GEN-LAST:event_jB00ActionPerformed

    private void jB0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB0ActionPerformed
        // TODO add your handling code here:
        if(lastButtonPressed.equals("jBequal"))
            jLabel1.setText(""+0);
        String be = jLabel1.getText();
        if(be.equals("0"))
           be = "0";
        else
           be += "0";
        jLabel1.setText(be);
        lastButtonPressed = "jB0";

    }//GEN-LAST:event_jB0ActionPerformed

    private void jBaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBaddActionPerformed
        // TODO add your handling code here:
        String be = jLabel1.getText();
        if(be.equals("0"))
           be = "0";
        else{
           Coper = '+';
           be += "+";
        }
        haveDec = false;
        lastButtonPressed = "jBadd";
        jLabel1.setText(be);
    }//GEN-LAST:event_jBaddActionPerformed

    private void jBdecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBdecActionPerformed
        // TODO add your handling code here:
        String be = jLabel1.getText();
        int len = be.length();
        if(!haveDec)
        {
            if(be.equals("0"))
                be = "0.";
            else {
                switch(be.charAt(len-1)){
                    case '+':
                    case '-':
                    case '/':
                    case '*':
                        be += "0.";
                        break;
                    default:
                        be += ".";
                }
            }
        }
        lastButtonPressed = "jBdec";
        haveDec = true;
        jLabel1.setText(be);
    }//GEN-LAST:event_jBdecActionPerformed

    private void jBacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBacActionPerformed
        // TODO add your handling code here:
        resetAll();
        lastButtonPressed = "jBac";
    }//GEN-LAST:event_jBacActionPerformed

    private void jBdivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBdivActionPerformed
        String be = jLabel1.getText();
        if(be.equals("0"))
           be = "0";
        else{
           Coper = '/';
           be += "/";
        }
        lastButtonPressed = "jBdiv";
        haveDec = false;
        jLabel1.setText(be);
    }//GEN-LAST:event_jBdivActionPerformed

    private void jBmulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmulActionPerformed
        // TODO add your handling code here:
        String be = jLabel1.getText();
        if(be.equals("0"))
           be = "0";
        else{
           Coper = '*';
           be += "*";
        }
        haveDec = false;
        jLabel1.setText(be);
    }//GEN-LAST:event_jBmulActionPerformed

    private void jBequal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBequal1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jBequal1ActionPerformed

    private void jBdelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBdelActionPerformed
        // TODO add your handling code here:
        jLabel1.setText(jLabel1.getText().substring(0,jLabel1.getText().length()-1));
    }//GEN-LAST:event_jBdelActionPerformed

    private void jMaboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMaboutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMaboutActionPerformed

    private void jMtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMtypeActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jMtypeActionPerformed

    private void jMIScientificActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIScientificActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new CalScientificUI().setVisible(true);
    }//GEN-LAST:event_jMIScientificActionPerformed

    private void jMInisHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMInisHActionPerformed
        // TODO add your handling code here:
        new AboutUI().setVisible(true); 
    }//GEN-LAST:event_jMInisHActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        new AboutUI().setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLabel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorUI().setVisible(true);
            }
        });
    }
    
public void keyPressed(KeyEvent e) {
    if (e.getKeyCode()==KeyEvent.VK_ENTER){
        ScriptEngineManager factory = new ScriptEngineManager();
        // create a JavaScript engine
        ScriptEngine engine = factory.getEngineByName("JavaScript");
        
        double d =0;
        
        try {
            d = (Double)engine.eval(jLabel1.getText()+"+0.0");
        } catch (ScriptException ex) {
            Logger.getLogger(CalculatorUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        jLabel1.setText(""+d);
        haveDec = true;
        lastButtonPressed = "jBequal";
    }                                       
    

}

    @Override
    public synchronized void addKeyListener(KeyListener l) {
        super.addKeyListener(l); //To change body of generated methods, choose Tools | Templates.
        
       }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB0;
    private javax.swing.JButton jB00;
    private javax.swing.JButton jB1;
    private javax.swing.JButton jB2;
    private javax.swing.JButton jB3;
    private javax.swing.JButton jB4;
    private javax.swing.JButton jB5;
    private javax.swing.JButton jB6;
    private javax.swing.JButton jB7;
    private javax.swing.JButton jB8;
    private javax.swing.JButton jB9;
    private javax.swing.JButton jBac;
    private javax.swing.JButton jBadd;
    private javax.swing.JButton jBdec;
    private javax.swing.JButton jBdel;
    private javax.swing.JButton jBdiv;
    private javax.swing.JButton jBequal;
    private javax.swing.JButton jBequal1;
    private javax.swing.JButton jBmul;
    private javax.swing.JButton jBsub;
    private javax.swing.JTextField jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem jMIScientific;
    private javax.swing.JMenuItem jMInisH;
    private javax.swing.JMenu jMabout;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMtype;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    private double findNum(String no) {
        return Double.parseDouble(no);
    }

    private void resetAll() {
        Coper = ' ';
        num2="";
        res = 0;
        n1=0;
        n2=0;
        haveDec = false;
        jLabel1.setText("0");
    }
}
